language: node_js
sudo: false
node_js:
  - "stable"

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0 # firefox virtual screen
  - sh -e /etc/init.d/xvfb start # firefox virtual screen
